Feat/communication request
InseeFr/Pearl-Jam pull request #110
Opened 2023-06-14 09:47 UTC by SimonDmz

2023-06-14 12:19 UTC, ddecrulle requested changes

2023-06-14 12:19 UTC, ddecrulle commented on src/components/panel-body/UEpage/communication/component.jsx
> +          onClickFunction={() => setOpenModal(true)}
it's a bad pratice to use arrow function in jsx because each time component is render, function are "created"

2023-06-14 12:19 UTC, ddecrulle commented on src/components/panel-body/UEpage/communication/component.jsx
> +        onClose={() => setOpenModal(false)}
arrow function in jsx

2023-06-14 12:19 UTC, ddecrulle commented on src/components/panel-body/UEpage/communication/component.jsx
> +          closeModalFunction={() => setOpenModal(false)}
arrow function in jsx

2023-06-14 12:19 UTC, ddecrulle commented on src/components/panel-body/UEpage/communication/form/CommunicationRequestForm.jsx
> +  ];
Move step outside component ?

2023-06-14 12:19 UTC, ddecrulle commented on src/components/panel-body/UEpage/communication/form/CommunicationRequestForm.jsx
> +      )}
I think (and sonar too) it's cleaner to use ternary conditional operator in this case

2023-06-14 12:19 UTC, ddecrulle commented on src/components/panel-body/UEpage/router.jsx
> +  );
Functional Components requires first letter be capitalized

2023-06-14 12:19 UTC, ddecrulle commented on src/components/panel-body/UEpage/router.jsx
> +              editionIcon={housingEditIcon}
This will imply that `icon={<HousingIcon />}` ...

2023-06-14 12:19 UTC, ddecrulle commented on src/utils/functions/communicationFunctions.js
> +};
Very strange code

2023-06-15 10:28 UTC, SimonDmz commented on src/components/panel-body/UEpage/communication/CommunicationRequestLine.jsx
> +  const lastStatus = status.sort((s1, s2) => s1.date < s2.date)[0];
js array doesn't access negative index like python, but could use of array.at(-1) from [HERE](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/at)

2023-06-20 07:36 UTC, ddecrulle commented on src/components/panel-body/UEpage/router.jsx
> +              editionIcon={housingEditIcon}
You have 2 choice : 
* `icon={<HousingIcon />}` in GenericTile component (props `icon` only) and in the jsx {icon} 
* Icon={HousingIcon} in GenericTile props `Icon` and in the jsx <Icon />

2023-06-26 12:08 UTC, ddecrulle approved these changes

2023-06-30 14:28 UTC, merged