feat : communication requests from the most recent one to the oldest one
InseeFr/Pearl-Jam pull request #158
Opened 2024-10-16 11:39 UTC by prwozny

… one by sorting by least recent status date com requests

2024-10-16 14:17 UTC, EmmanuelDemey requested changes

2024-10-16 14:17 UTC, EmmanuelDemey commented on src/ui/SurveyUnit/Communication/CommunicationConfirmation.tsx
> +                </Fragment>
```suggestion
                {address.locality.length > 0 && (
                  <>
                    {address.locality} <br />
                  </>
                )}
                <>
                  {address.postCode}, {address.cityName}
                </>
```

2024-10-16 14:17 UTC, EmmanuelDemey commented on src/ui/SurveyUnit/Communication/CommunicationConfirmation.tsx
> +                    {address.additionalAddress} <br />
```suggestion
                <>
                  {address.streetName} <br />
                </>
                {address.additionalAddress.length > 0 && (
                  <>
                    {address.additionalAddress} <br />
```

2024-10-16 14:17 UTC, EmmanuelDemey commented on src/ui/SurveyUnit/Communication/CommunicationsCard.tsx
> +  console.log(surveyUnitCommunicationRequests);
I think you can remove this console.log :P

2024-10-18 11:57 UTC, SimonDmz approved these changes

2024-10-18 11:58 UTC, merged