feat : business id support
InseeFr/Pearl-Jam pull request #159
Opened 2024-10-16 14:40 UTC by prwozny

2024-10-17 18:50 UTC, EmmanuelDemey requested changes

2024-10-17 18:50 UTC, EmmanuelDemey commented on src/pages/StatsTracking.tsx
> +  const handleSortChange = (direction: React.SetStateAction<string>) => {
Do you need to add the extra React before SetStateAction?

2024-10-17 18:50 UTC, EmmanuelDemey commented on src/pages/StatsTracking.tsx
> +  const [sortDirection, setSortDirection] = useState('');
We can maybe type correctly this variable.? It can accept only defined list of string values.

2024-10-18 12:14 UTC, SimonDmz requested changes
change the version in package.json too 😉

2024-10-18 12:14 UTC, SimonDmz commented on src/i18n/trackingMessage.js
> +    en: 'Lastname/FirstName, Id, Nusiness Id',
typo Business

2024-10-18 12:14 UTC, SimonDmz commented on src/i18n/trackingMessage.js
> +    sq: 'Mbiemri/Emri',
```suggestion
    sq: 'Mbiemri/Emri, id, id i njësisë',
```
🇦🇱 ✊

2024-10-18 12:14 UTC, SimonDmz commented on src/ui/SurveyCard.tsx
> +              #{surveyUnit.displayName ? surveyUnit.displayName : surveyUnit.id}
```suggestion
              #{surveyUnit.displayName ?? surveyUnit.id}
```

2024-10-18 12:14 UTC, SimonDmz commented on src/pages/TableTracking.tsx
> +                eeeee
??? => to remove

2024-10-18 12:14 UTC, SimonDmz commented on src/pages/TableTracking.tsx
> +            `#${surveyUnit.displayName ? surveyUnit.displayName : surveyUnit.id}`
```suggestion
            `#${surveyUnit.displayName ?? surveyUnit.id}`
```

2024-10-18 12:14 UTC, SimonDmz commented on src/pages/TableTracking.tsx
> +              #{surveyUnit.displayName ? surveyUnit.displayName : surveyUnit.id}
```suggestion
              #{surveyUnit.displayName ?? surveyUnit.id}
```

2024-10-21 09:53 UTC, SimonDmz approved these changes

2024-10-21 09:54 UTC, merged